apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-peer0
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: carrier-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-demo-fabric
        namespace: flux-demo-fabric
      chart: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: carrier-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.carrier-net:7051
      gossipexternalendpoint: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.2
      couchdb:
        username: carrier-user

    storage:
      peer:
        storageclassname: carriersc
        storagesize: 512Mi
      couchdb:
        storageclassname: carriersc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://a512e00204ace430bb7a6f6e15a9fb56-1690181827.us-east-1.elb.amazonaws.com:8200
      authpath: demo-fabriccarrier-net-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/carrier-net/peers/peer0.carrier-net
      secretambassador: secretsv2/data/crypto/peerOrganizations/carrier-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secretsv2/data/credentials/carrier-net/couchdb/carrier?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "none"
      external_url_suffix: develop.local.com

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
