##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Default values for indy-key-mgmt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  #Provide the namespace for organization's peer
  #Eg. namespace: supplychain-bes
  namespace:

  #Provide the name for indy-key-mgmt release
  #Eg. name: indy-key-mgmt
  name:

image:
  #Provide the image repository for the indy-key-mgmt container
  #Eg. repository: indy-key-mgmt:latest
  repository:

  #Provide the image pull secret of image
  #Eg. pullSecret: regcred
  pullSecret:


vault:
  #Provide the vault server address
  #Eg. address: http://54.226.163.39:8200
  address:

  #Provide the key path for vault
  #Eg. authpath: provider.stewards
  authpath:

  #Provide the identity for vault
  #Eg. role: my-identity
  role:

  # Provide the service account name autheticated to vault.
  # NOTE: Make sure that the service account is already created and autheticated to use the vault.
  # Eg. serviceAccountName: vault-auth
  serviceaccountname: 

  # Provide the vault path where the tm secrets are stored
  # Eg. secretprefix: secret/warehouse-bes/crypto/warehouse/tm
  tmprefix: 
  # Number of retries to check contents from vault 
  retries:

#############################################################
#                       Settings                            #
############################################################# 
# sleep time in seconds when error while registration
# Ex. sleepTimeAfterError: 120
sleepTimeAfterError: 120
# custom sleep time in seconds
sleepTime: 20
healthcheck:
  #Provide the wait interval in seconds in fetching certificates from vault
  #Eg. readinesscheckinterval: 5
  readinesscheckinterval: 5
  #Provide the threshold number of retries in fetching certificates from vault
  #Eg. readinessthreshold: 2
  readinessthreshold: 2
