##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

############################################################################################
# Add the smart contract address to the vault
- name: "Putting contract address {{contract_address}} to vault of {{ organization_data.name | lower }}"
  shell: |
    vault kv put {{ component_vault.secret_path | default('secretsv2') }}/{{component_ns}}/smartContracts/{{contract_name}} address="$(echo ${ADDRESS} )" 
  environment:
    VAULT_ADDR: "{{ component_vault.url }}"
    VAULT_TOKEN: "{{ component_vault.root_token }}"
    ADDRESS: "{{ contract_address }}"
