##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: A Helm3 chart for Running Indy Ledger Script for Issuing a NYM Transaction
name: indy-ledger-chart
version: "1.0.0"
