##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: A Helm3 chart for job indy-auth-job
name: indy-auth-job
version: "1.0.0"
