##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "1.0"
description: A Helm3 chart for Ambassador certificates creation
name: certs-ambassador-quorum
version: 0.1.0
