##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

helm_templates:
  webserver: webserver.tpl
  university: university.tpl
  employer: employer.tpl
