apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: manufacturer-net-ca-tools
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: manufacturer-net-ca-tools
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-demo-fabric
        namespace: flux-demo-fabric
      chart: platforms/hyperledger-fabric/charts/catools
  values:
    metadata:
      namespace: manufacturer-net
      name: ca-tools
      component_type: peer
      org_name: manufacturer
      proxy: none
    replicaCount: 1

    image:
      repository: hyperledger/fabric-ca-tools
      tag: 1.2.1
      pullPolicy: IfNotPresent
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      
    storage:
      storageclassname: manufacturersc
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://a512e00204ace430bb7a6f6e15a9fb56-1690181827.us-east-1.elb.amazonaws.com:8200
      authpath: demo-fabricmanufacturer-net-auth
      secretmsp: secretsv2/data/crypto/peerOrganizations/manufacturer-net/users/admin/msp
      secrettls: secretsv2/data/crypto/peerOrganizations/manufacturer-net/users/admin/tls
      secretorderer: secretsv2/data/crypto/peerOrganizations/manufacturer-net/orderers
      secretpeer: secretsv2/data/crypto/peerOrganizations/manufacturer-net/peers
      secretpeerorderertls: secretsv2/data/crypto/peerOrganizations/manufacturer-net/orderer/tls
      secretambassador: secretsv2/data/crypto/peerOrganizations/manufacturer-net/ambassador
      secretcert: secretsv2/data/crypto/peerOrganizations/manufacturer-net/ca?ca.manufacturer-net-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/manufacturer-net/ca?manufacturer-net-CA.key
      secretcouchdb: secretsv2/data/credentials/manufacturer-net/couchdb/manufacturer
      secretconfigfile: secretsv2/data/crypto/peerOrganizations/manufacturer-net/msp/config
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: develop.local.com
      component_subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      cert_subject: O=Manufacturer/OU=Manufacturer/L=47.38,8.54,Zurich/C=CH
      component_country: CH
      component_state: Zurich
      component_location: Zurich
      ca_url: ca.manufacturer-net:7054

    orderers:
      name: orderer1-
    orderers_info:
      - name: orderer1
        path: "certs/orderer1-ca.crt"

    peers:
      name: peer0,-      
    peer_count: "1"
    checks:
      refresh_cert_value: False
      add_peer_value: False
