##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
# This role deletes the helm releases and uninstalls Flux
#############################################################################################

# Remove all Helm installations
- name: Remove all Helm installations of namespace {{ org.name | lower }}
  args:
    executable: /bin/bash
  shell: |
    helm_releases=($(KUBECONFIG={{ k8s.config_file }} helm ls -A | grep {{ org.name | lower }} | awk '{print $1}'))
    for helm_release in "${helm_releases[@]}"
    do
      KUBECONFIG={{ k8s.config_file }} helm uninstall ${helm_release}
    done
  ignore_errors: yes

- name: Deletes namespaces
  k8s:
    kind: Namespace
    name: "{{ component_ns }}"
    state: absent
    kubeconfig: "{{ k8s.config_file }}"
    context: "{{ k8s.context }}"
  ignore_errors: yes
