##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: A Helm3 chart for indy-node StatefulSet
name: indy-node
version: "1.0.0"
