##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: A Helm chart to deploy Hyperledger Besu nodes with orion transaction manager
name: node_validator
version: 0.2.0
