##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

springboot_image_tag:
  4.1: springboot-0.4.1.0
  4.4: springboot-0.4.2.0
  4.7: springboot-0.11.0.0
