##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: A Helm chart to deploy Quorum nodes with constellation transaction manager
name: node_constellation
version: 0.2.0
