##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Build bevel-build docker image triggered by :
#  - push on develop branch for latest tags 
#  - create tag vx.y.z for release tags
#  - Can be triggered manually

name: Build Bevel Docker container

on:
  workflow_dispatch:
  create:
    tags:
      - v*
  push:
    branches:
      - develop
    paths:
      - 'Dockerfile'
      - 'Dockerfile.jkd8'
      - '.github/workflows/docker_build.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository_owner }}

jobs:
  # on push to develop branch, create docker tags latest and jdk8-latest
  bevel-build-latest:
    if: ${{ startsWith(github.ref, 'refs/heads/develop') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push release tag latest
      id: docker_build_latest
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_PATH }}/bevel-build:latest
    
    - name: Build and push tag jdk8-latest
      id: docker_build_jdk8_latest
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.jdk8
        push: true
        tags: ${{ env.IMAGE_PATH }}/bevel-build:jdk8-latest

  # on tag vx.y.z created, create docker tag stable, x.y.z and jdk8
  bevel-build-release: 
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push release and stable tag ${{ steps.vars.outputs.tag }}  
      id: docker_build_release
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_PATH }}/bevel-build:${{ steps.vars.outputs.tag }},${{ env.IMAGE_PATH }}/bevel-build:stable
    
    - name: Build and push tag jdk8-latest
      id: docker_build_jdk8
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile.jdk8
        push: true
        tags: ${{ env.IMAGE_PATH }}/bevel-build:jdk8-stable,${{ env.IMAGE_PATH }}/bevel-build:jdk8-${{ steps.vars.outputs.tag }}
