##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Build Supplychain-App quorum docker images triggered by :
#  - push on develop branch for latest tags 
#  - create tag vx.y.z for release tags
#  - Can be triggered manually

name: Build Supplychain App Quorum Images

on:
  workflow_dispatch:
  create:
    tags:
      - v*
  push:
    branches:
      - develop
    paths:
      - 'examples/supplychain-app/quorum/**'
      - '.github/workflows/quorum_images_build.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository_owner }}

jobs:
  # on push to develop branch, create docker tags latest
  quorum-latest:
    if: ${{ startsWith(github.ref, 'refs/heads/develop') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push supplychain app latest
      id: quorum_supplychain_latest
      uses: docker/build-push-action@v2
      with:
        context: examples/supplychain-app/quorum/express_nodeJS
        push: true
        tags: ${{ env.IMAGE_PATH }}/bevel-supplychain-quorum:express-app-latest

  quorum-release: 
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push supplychain app release
      id: quorum_supplychain_release
      uses: docker/build-push-action@v2
      with:
        context: examples/supplychain-app/quorum/express_nodeJS
        push: true
        tags: ${{ env.IMAGE_PATH }}/bevel-supplychain-quorum:express-app-${{ steps.vars.outputs.tag }},${{ env.IMAGE_PATH }}/bevel-supplychain-quorum:express-app-stable
